### PR TITLE
Use ssb-db2

### PR DESCRIPTION
**Pull request by staltz**

### CODE REVIEW

**Comment by KyleMaas** [comment]
Looking forward to this being merged.  I think we could use this in ssb-browser-demo to make the UI a little easier to navigate.

**Comment by staltz** [comment]
This is not in shape for a merge. I still get wildly broken behavior

**Comment by KyleMaas** [comment]
No problem.  But whenever this is ready, I'm looking forward to using it.  What you're doing here is important.

**Comment by staltz** [comment]
@KyleMaas By the way, you can test version `7.0.0-rc4` published on npm

**Comment by KyleMaas** [comment]
@staltz Excellent.  I didn't expect you to get this going quite this quickly so I've still got a couple things I'd like to work on first.  But I will try it as soon as I can.  Thanks!

**Comment by KyleMaas** [comment]
This does seem to work pretty well.  I did file a few issues that would make it easier to use, though.

**Comment by staltz** [comment]
@KyleMaas version 7.0.0 is out

**Comment by KyleMaas** [comment]
@staltz Excellent.  I used it for this:

https://github.com/arj03/ssb-browser-demo/pull/252

Which has been working pretty well for me.  I'll give the new version a try in a bit.

**Comment by KyleMaas** [comment]
Getting rid of the `opts.limit` option kind of threw me for a second.  But got it fixed up.

**Pull request merged**
